# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neo4jCli < Formula
  desc "Command-line interface for Neo4j"
  homepage "https://github.com/neo4j/cli"
  version "1.14.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neo4j-labs/neo4j-cli/releases/download/v1.14.0/neo4j-cli_1.14.0_Darwin_x86_64.tar.gz"
      sha256 "336996e63079d9032630b44e99e40f7bed3ff43483d00cfa1732d85a3837665d"

      define_method(:install) do
        bin.install "neo4j-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neo4j-labs/neo4j-cli/releases/download/v1.14.0/neo4j-cli_1.14.0_Darwin_arm64.tar.gz"
      sha256 "cd90346c8302d5e906ac8212c366c90da69549c1c752783b6a64bfca9a64d528"

      define_method(:install) do
        bin.install "neo4j-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neo4j-labs/neo4j-cli/releases/download/v1.14.0/neo4j-cli_1.14.0_Linux_x86_64.tar.gz"
      sha256 "6df4e50ee0650c70116dcede1ccd19b613899c658461abd96e4328791dfd01b6"
      define_method(:install) do
        bin.install "neo4j-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neo4j-labs/neo4j-cli/releases/download/v1.14.0/neo4j-cli_1.14.0_Linux_arm64.tar.gz"
      sha256 "9620e2da2f48fdc1ba22a3db3fe07eaf621b3dfa5e61506584cd5ac700dce2d0"
      define_method(:install) do
        bin.install "neo4j-cli"
      end
    end
  end

  def post_install
    return unless ENV["NEO4J_CLI_AUTO_INSTALL_SKILL"] == "1"
    system "#{bin}/neo4j-cli", "skill", "install", "--rw"
    true
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/neo4j-cli --version")
  end
end
